-- USER SQL
CREATE USER CAMPING IDENTIFIED BY "camping"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT "CONNECT" TO CAMPING ;
GRANT "RESOURCE" TO CAMPING ;
ALTER USER CAMPING DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT ALTER SESSION TO CAMPING ;
GRANT CREATE VIEW TO CAMPING ;
GRANT CREATE SESSION TO CAMPING ;
GRANT CREATE TABLE TO CAMPING ;
GRANT CREATE SYNONYM TO CAMPING ;
GRANT CREATE DATABASE LINK TO CAMPING ;
GRANT UNLIMITED TABLESPACE TO CAMPING ;

